### ISSUE TITLE
Does not compile with kernel 5.16

### ISSUE THREAD

**Issue by UncleGrumpy** [gschorcht/spi-ch341-usb#21]
using kernel 5.16 make fails to build, here is the output:

> make
make -C /lib/modules/5.16.8-arch1-1/build M=/home/winford/github/gschorcht/spi-ch341-usb  modules
make[1]: Entering directory '/usr/lib/modules/5.16.8-arch1-1/build'
CC [M]  /home/winford/github/gschorcht/spi-ch341-usb/spi-ch341-usb.o
/home/winford/github/gschorcht/spi-ch341-usb/spi-ch341-usb.c: In function ‘ch341_spi_probe’:
/home/winford/github/gschorcht/spi-ch341-usb/spi-ch341-usb.c:598:33: error: implicit declaration of function ‘spi_busnum_to_master’ [-Werror=implicit-function-declaration]
598 |     while ((ch341_dev->master = spi_busnum_to_master(bus)))
|                                 ^~~~~~~~~~~~~~~~~~~~
/home/winford/github/gschorcht/spi-ch341-usb/spi-ch341-usb.c:598:31: warning: assignment to ‘struct spi_controller *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
598 |     while ((ch341_dev->master = spi_busnum_to_master(bus)))
|                               ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:287: /home/winford/github/gschorcht/spi-ch341-usb/spi-ch341-usb.o] Error 1
make[1]: *** [Makefile:1846: /home/winford/github/gschorcht/spi-ch341-usb] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.8-arch1-1/build'
make: *** [Makefile:20: spi-ch341-usb.ko] Error 2

I tried using the patch from pull request #20 and can verify that fixes the problem and works well.  Please take a look at that pull request.
